version: '3.8'

services:
  # Frontend (React/Vite)
  web:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:3001
    depends_on:
      - api

  # Backend (Node.js/Express)
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./models:/app/models
      - ./uploads:/app/uploads
    environment:
      - MONGO_URI=mongodb://mongo:27017/samsung-reflect
      - PORT=3001
      - NODE_ENV=development
      - SERVER_INFERENCE=true
      - MODEL_DIR=/app/models
      - VECTOR_DB_URL=http://qdrant:6333
      - REDIS_URL=redis://redis:6379
      - PYTHON_SERVICE_URL=http://python-ml:8000
    depends_on:
      - mongo
      - redis
      - qdrant
      - python-ml

  # Python ML Service (FastAPI)
  python-ml:
    build:
      context: ./ml-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./uploads:/app/uploads
    environment:
      - MODEL_DIR=/app/models
      - MIN_DETECTION_SCORE=0.25
      - NMS_IOU_THRESHOLD=0.45
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  # MongoDB
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=samsung-reflect

  # Redis (for job queue)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # Qdrant Vector Database
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334

volumes:
  mongo_data:
  redis_data:
  qdrant_data:
